### ISSUE TITLE
Improve colour contrast on dark theme (primary blue)

### ISSUE THREAD

**Issue by trallard** [2i2c-org/sphinx-2i2c-theme#26]
### Context

I was having a look at your lovely team compass - because it is an absolute gem 💎 - and while the new branding and colours are beautiful, the primary blue colour (`#1D4AE5`) has poor contrast in dark mode (currently, it's 1:2.7 when the recommended for accessibility is 1:4.5 minimum, screenshot attached)

![Colour_Contrast_Analyser__CCA__and_Where_to_look_for_information_—_Team_Compass](https://github.com/2i2c-org/sphinx-2i2c-theme/assets/23552331/2bf7b0ca-db87-4c1d-bc6e-94d6cfc7544c)

Ignore that the foreground/background are inverted in my contrast checker it's just because of the order in which I added the colours.

### Proposal

 I know that making colour changes, especially when tied to a brand, can be tricky - but perhaps for the dark theme, the blue colour could be adjusted to something like `#5077FC` to make 
 this more readable (contextualised reference [colour.review/check/5077FC-14181F](colour.review/check/5077FC-14181F))

I am adding a screenshot with a direct override for reference, too - the readability improvement is considerable, in my opinion.

![Colour_Contrast_Analyser__CCA__and_Organizational_structure_—_Team_Compass](https://github.com/2i2c-org/sphinx-2i2c-theme/assets/23552331/a465e973-7b98-46b7-bcfd-d972ed71a41a)

I would be happy to help with any colour-related improvements if needed, just give me a shout.

**Comment by choldgraf** [comment]
I think this is totally fine especially for text and menu items. IMO "is the color the technical brand blue" doesn't matter as much in this context because people's perception of the blue is going to change significantly when you go from light/dark anyway. So it is effectively a different blue even if technically it is the same blue. I think that means it's fine to change it for accessibility purposes.

Got a PR to implement here: https://github.com/2i2c-org/sphinx-2i2c-theme/pull/27

Seemed easier to just make that quickly than to give you a full rundown of our sphinx sub-theming situation 😅
